name: Build with Pandoc

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
        BUILD_BRANCH: gh-pages
    steps:
      - name: Checkout current branch
        uses: actions/checkout@master
      - name: Build with Pandoc
        uses: docker://mitinarseny/panmake:latest
        with:
          entrypoint: make
          args: pdf
      - name: GitHub Pages Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
